import type { SearchSort } from "@/lib/config/marketplace";

/** Buyer-visible Azerbaijani labels (single place — no English in UI). */
export const CATEGORY_LABELS: Record<string, string> = {
  CAR: "Avtomobil",
  MOTORCYCLE: "Motosiklet",
};

export const SORT_LABELS: Record<SearchSort, string> = {
  NEWEST: "Ən yeni",
  PRICE_ASC: "Qiymət: artan",
  PRICE_DESC: "Qiymət: azalan",
  YEAR_DESC: "İl: yenidən köhnəyə",
};

export const STATUS_LABELS = {
  SOLD: "Satılıb",
  EXPIRED: "Müddəti bitib",
} as const;

export const UI = {
  brand: "AVTOSH.AZ",
  listings: "Elanlar",
  cars: "Avtomobillər",
  motorcycles: "Motosikletlər",
  postListing: "Elan yerləşdir",
  login: "Daxil ol",
  search: "Axtar",
  brandLabel: "Marka",
  modelLabel: "Model",
  city: "Şəhər",
  price: "Qiymət",
  year: "Buraxılış ili",
  mileage: "Yürüş",
  showMore: "Daha çox göstər",
  clearFilters: "Filterləri təmizlə",
  applyFilters: "Tətbiq et",
  filters: "Filterlər",
  sort: "Sıralama",
  premium: "Premium elanlar",
  promoted: "Reklam",
  premiumBadge: "Premium",
  boostedBadge: "Reklam",
  loading: "Yüklənir…",
  noResults: "Uyğun elan tapılmadı",
  noResultsHint: "Filterləri dəyişin və ya təmizləyin.",
  errorTitle: "Xəta baş verdi",
  errorHint: "Zəhmət olmasa bir az sonra yenidən cəhd edin.",
  invalidFilters: "Axtarış parametrləri düzgün deyil",
  notFoundTitle: "Elan tapılmadı",
  notFoundHint: "Bu elan mövcud deyil və ya artıq göstərilmir.",
  backHome: "Ana səhifəyə qayıt",
  showPhone: "Nömrəni göstər",
  callSeller: "Zəng et",
  whatsapp: "WhatsApp ilə yaz",
  contactUnavailable: "Əlaqə məlumatı mövcud deyil",
  contactRateLimited: "Çox sayda cəhd edildi. Bir az sonra yenidən yoxlayın.",
  seller: "Satıcı",
  description: "Təsvir",
  features: "Təchizat",
  specs: "Xüsusiyyətlər",
  any: "Hamısı",
  min: "min",
  max: "maks",
  credit: "Kredit",
  barter: "Barter",
  imageUnavailable: "Şəkil yoxdur",
  photoOf: "Şəkil",
  // Auth & favorites (Phase 4.10)
  loginTitle: "Daxil ol və ya qeydiyyatdan keç",
  loginHint: "Telefon nömrənizə WhatsApp ilə təsdiq kodu göndəriləcək.",
  phoneLabel: "Telefon nömrəsi",
  phonePlaceholder: "+994 50 123 45 67",
  sendCode: "Kod göndər",
  otpLabel: "Təsdiq kodu",
  otpHint: "WhatsApp-a göndərilən 6 rəqəmli kodu daxil edin.",
  otpSentTo: "Kod göndərildi:",
  verify: "Təsdiqlə",
  resend: "Kodu yenidən göndər",
  resendIn: "Yenidən göndərmə:",
  changePhone: "Nömrəni dəyiş",
  invalidPhone: "Telefon nömrəsi düzgün deyil.",
  otpInvalid: "Kod düzgün deyil. Yenidən cəhd edin.",
  otpExpired: "Kodun müddəti bitib. Yeni kod istəyin.",
  otpLocked: "Çox sayda səhv cəhd. Yeni kod istəyin.",
  otpRateLimited: "Çox sayda cəhd edildi. Bir az sonra yenidən yoxlayın.",
  logout: "Çıxış",
  profile: "Profil",
  favorites: "Seçilmişlər",
  favoritesEmpty: "Hələ seçilmiş elanınız yoxdur",
  favoritesEmptyHint: "Bəyəndiyiniz elanları ürək işarəsi ilə yadda saxlayın.",
  addFavorite: "Seçilmişlərə əlavə et",
  removeFavorite: "Seçilmişlərdən çıxar",
  listingInactive: "Elan artıq aktiv deyil",
  account: "Hesabım",
  accountBlocked: "Hesabınız bloklanıb. Baxış mümkündür, yeni əməliyyatlar məhdudlaşdırılıb.",
  myListings: "Elanlarım",
} as const;

/** Seller wizard & My Listings strings (Phase 4.11). */
export const SELLER = {
  newListing: "Yeni elan",
  continueDraft: "Davam et",
  editListing: "Redaktə et",
  fixListing: "Düzəliş et",
  viewListing: "Elana bax",
  createListing: "Elan yarat",
  chooseCategory: "Kateqoriya seçin",
  existingDrafts: "Yarımçıq elanlarınız",
  steps: ["Nəqliyyat", "Məlumatlar", "Şəkillər", "Təsvir və əlaqə", "Yoxla və göndər"],
  stepLabel: "Addım",
  back: "Geri",
  next: "İrəli",
  category: "Kateqoriya",
  brand: "Marka",
  model: "Model",
  year: "Buraxılış ili",
  price: "Qiymət, AZN",
  mileage: "Yürüş, km",
  engineCc: "Mühərrik, sm³",
  city: "Şəhər",
  credit: "Kredit mümkündür",
  barter: "Barter mümkündür",
  features: "Təchizat",
  description: "Təsvir",
  descriptionHint: "Nəqliyyat vasitəsi haqqında ətraflı yazın (maks. 5000 simvol).",
  contactPhone: "Əlaqə nömrəsi",
  contactPhoneHint: "Alıcılar bu nömrəni görəcək, məsələn +994501234567.",
  select: "Seçin",
  notSelected: "Seçilməyib",
  saving: "Yadda saxlanılır…",
  saved: "Yadda saxlanıldı",
  saveError: "Yadda saxlanmadı. Yenidən cəhd edin.",
  conflictTitle: "Elan başqa pəncərədə dəyişdirilib.",
  conflictHint: "Davam etmək üçün son vəziyyəti yükləyin. Bu pəncərədəki yadda saxlanmamış dəyişikliklər itəcək.",
  conflictReload: "Son vəziyyəti yüklə",
  photos: "Şəkillər",
  addPhotos: "Şəkil əlavə et",
  photoFormats: "JPEG, PNG və ya WebP, maks. 12 MB. Minimum 3 şəkil tələb olunur.",
  photoUnsupported: "Bu format dəstəklənmir. JPEG, PNG və ya WebP seçin.",
  photoTooLarge: "Şəkil çox böyükdür (maks. 12 MB).",
  photoUploadFailed: "Şəkil yüklənmədi. Yenidən cəhd edin.",
  photoUploading: "Yüklənir…",
  photoProcessing: "Emal olunur…",
  photoLimitReached: "Maksimum şəkil sayına çatdınız.",
  primaryPhoto: "Əsas şəkil",
  makePrimary: "Əsas şəkil et",
  moveLeft: "Sola çək",
  moveRight: "Sağa çək",
  deletePhoto: "Şəkli sil",
  preview: "Önizləmə",
  completenessTitle: "Göndərməzdən əvvəl tamamlayın",
  completenessDone: "Elan göndərilməyə hazırdır",
  minPhotos: "Ən azı 3 şəkil",
  submit: "Moderasiyaya göndər",
  resubmit: "Yenidən göndər",
  submitting: "Göndərilir…",
  submittedFree: "Elanınız moderasiyaya göndərildi",
  submittedFreeHint: "Yoxlamadan sonra elanınız dərc olunacaq. Nəticə barədə məlumat veriləcək.",
  paymentRequired: "Ödəniş tələb olunur",
  paymentRequiredHint: "İlk 3 elan pulsuzdur. Bu elanın dərci üçün ödəniş tələb olunur.",
  paymentAfterHint: "Ödənişdən sonra elanınız moderasiyaya göndəriləcək.",
  payNow: "Ödəniş et",
  payInitiating: "Ödəniş səhifəsi hazırlanır…",
  payInitFailed: "Ödəniş başladıla bilmədi. Bir az sonra yenidən cəhd edin.",
  paySuccessTitle: "Ödəniş uğurla tamamlandı",
  paySuccessHint: "Elanınız moderasiyaya göndərildi. Yoxlamadan sonra dərc olunacaq.",
  payPendingTitle: "Ödəniş hələ təsdiqlənməyib",
  payPendingHint: "Ödəniş etmisinizsə, bir az sonra yenidən yoxlayın. Kartınızdan vəsait çıxıbsa, təkrar ödəniş etməyin.",
  payFailedTitle: "Ödəniş tamamlanmadı",
  payFailedHint: "Ödəniş ləğv edildi və ya bank tərəfindən qəbul edilmədi. Yenidən cəhd edə bilərsiniz.",
  payRefundedTitle: "Ödəniş geri qaytarılıb",
  payRefundedHint: "Bu ödəniş geri qaytarılıb. Suallarınız üçün dəstəklə əlaqə saxlayın.",
  payCheckAgain: "Yenidən yoxla",
  payRetry: "Yenidən cəhd et",
  payCheckingTitle: "Ödəniş yoxlanılır",
  payUnknownTitle: "Ödəniş məlumatı tapılmadı",
  payUnknownHint: "Bu ödəniş bu hesabla əlaqələndirilməyib və ya keçid düzgün deyil.",
  promote: "İrəli çək",
  promotionTitle: "Elanı irəli çək",
  premiumDescription: "Elanınız ana səhifədəki Premium bölməsində göstərilir.",
  boostDescription: "Elanınız axtarışda uyğun nəticələrin yuxarısında göstərilir.",
  promotionConfirmTitle: "Sifarişi təsdiqləyin",
  promotionService: "Xidmət",
  promotionDuration: "Müddət",
  promotionPrice: "Qiymət",
  promotionDay: "gün",
  premiumActive: "Premium aktivdir",
  boostActive: "Boost aktivdir",
  promotionUntil: "tarixinədək",
  promotionQueuedHint: "Yeni müddət mövcud müddətin bitməsindən sonra əlavə olunacaq.",
  premiumActivated: "Premium aktiv edildi",
  boostActivated: "Boost aktiv edildi",
  promotionActivatedHint: "Elanınız seçilmiş müddət ərzində irəli çəkiləcək.",
  promotionNotAvailable: "Bu elan üçün irəli çəkmə hazırda mümkün deyil.",
  promotionPackagesUnavailable: "Təşviq paketləri hazırda əlçatan deyil.",
  promotionPackagesUnavailableHint: "Paketlər aktiv olan kimi bu səhifədə görünəcək.",
  promotionOnlyActiveHint: "İrəli çəkmə yalnız aktiv elanlar üçün mümkündür.",
  payGenericTitle: "Ödəniş statusu yoxlanıldı",
  payGenericHint: "Hesabınıza daxil olaraq elanınızın vəziyyətinə baxa bilərsiniz.",
  payCheckFailedTitle: "Ödəniş yoxlanıla bilmədi",
  payCheckFailedHint: "Bank ilə əlaqə müvəqqəti mümkün olmadı. Ödəniş vəziyyətiniz dəyişməyib.",
  quotaFreeRemaining: "Pulsuz elan haqqınız:",
  quotaFree: "Bu elan pulsuz dərc olunacaq (ilk 3 elan pulsuzdur).",
  quotaPaid: "Bu elanın dərci ödənişlidir:",
  moderationPending: "Elanınız moderasiyadadır",
  moderationPendingHint: "Yoxlama tamamlanan kimi nəticə görünəcək.",
  moderationFeedback: "Moderator rəyi",
  incompleteTitle: "Elan natamamdır",
  insufficientImages: "Şəkil sayı kifayət deyil — ən azı 3 təsdiqlənmiş şəkil lazımdır.",
  invalidCatalog: "Seçimlərdən biri artıq mövcud deyil. Kataloq seçimlərini yeniləyin.",
  blockedTitle: "Hesabınız bloklanıb",
  blockedHint: "Yeni elan yerləşdirmək və redaktə etmək mümkün deyil.",
  emptyMyListings: "Hələ elanınız yoxdur",
  emptyMyListingsHint: "İlk elanınızı bir neçə dəqiqəyə yerləşdirin.",
  filterAll: "Hamısı",
  filterActive: "Aktiv",
  filterModeration: "Moderasiya",
  filterDraft: "Qaralama",
  filterCorrection: "Düzəliş",
  photosCount: "şəkil",
  unsavedLeaveWarning: "Yadda saxlanmamış dəyişikliklər var.",
} as const;

export const SPEC_LABELS = {
  fuelType: "Yanacaq",
  transmission: "Sürətlər qutusu",
  bodyType: "Ban növü",
  driveType: "Ötürücü",
  motorcycleType: "Motosiklet növü",
  color: "Rəng",
  engineCc: "Mühərrik",
  mileage: "Yürüş",
  year: "Buraxılış ili",
  city: "Şəhər",
  credit: "Kredit",
  barter: "Barter",
} as const;

export const GROUP_LABELS: Record<string, string> = {
  FUEL_TYPE: "Yanacaq",
  TRANSMISSION: "Sürətlər qutusu",
  BODY_TYPE: "Ban növü",
  DRIVE_TYPE: "Ötürücü",
  MOTORCYCLE_TYPE: "Motosiklet növü",
  COLOR: "Rəng",
};

/** Moderator portal strings (Phase 4.14). Staff-facing Azerbaijani. */
export const STAFF = {
  portal: "Moderasiya",
  queue: "Moderasiya növbəsi",
  queueEmpty: "Növbə boşdur — yoxlanılacaq elan yoxdur.",
  queueError: "Növbə yüklənmədi. Yenidən cəhd edin.",
  loadMore: "Daha çox göstər",
  submittedAt: "Göndərilib",
  seller: "Satıcı",
  review: "Elan yoxlaması",
  claim: "Nəzarətə götür",
  claimMine: "Sizin nəzarətinizdədir",
  claimOther: "Başqa moderatorun nəzarətindədir",
  claimFree: "Nəzarətdə deyil",
  claimUntil: "qədər",
  claimTaken: "Elan başqa moderator tərəfindən götürüldü.",
  claimRequired: "Qərar vermək üçün əvvəlcə elanı nəzarətə götürün.",
  approve: "Təsdiqlə",
  reject: "Rədd et",
  correction: "Düzəliş tələb et",
  suspend: "Dayandır",
  reason: "Səbəb",
  sellerNote: "Satıcı üçün qeyd",
  sellerNoteHint: "Bu mətn satıcıya olduğu kimi göstəriləcək. Maks. 1000 simvol.",
  confirmAction: "Təsdiq edin",
  confirm: "Bəli, təsdiqlə",
  cancel: "İmtina",
  approvedDone: "Elan təsdiqləndi və dərc olundu.",
  rejectedDone: "Elan rədd edildi.",
  correctionDone: "Düzəliş tələbi satıcıya göndərildi.",
  suspendedDone: "Elan dayandırıldı.",
  staleConflict: "Elan dəyişdirilib. Son versiyanı yeniləyin.",
  decisionAlready: "Bu elan üzrə qərar artıq verilib.",
  refresh: "Yenilə",
  actionFailed: "Əməliyyat alınmadı. Yenidən cəhd edin.",
  backToQueue: "Moderasiya növbəsinə qayıt",
  viewCurrent: "Cari vəziyyətə bax",
  history: "Moderasiya tarixçəsi",
  historyEmpty: "Əvvəlki yoxlama yoxdur.",
  decisionApproved: "Təsdiqlənib",
  decisionRejected: "Rədd edilib",
  decisionCorrection: "Düzəliş tələb olunub",
  images: "Şəkillər",
  primaryTag: "Əsas",
  noImage: "Şəkil yoxdur",
  specs: "Məlumatlar",
  descriptionTitle: "Təsvir",
  contactField: "Əlaqə nömrəsi",
  logout: "Çıxış",
  roleModerator: "Moderator",
  roleAdmin: "Admin",
} as const;
