import type { SearchSort } from "@/lib/config/marketplace";

/** Buyer-visible Azerbaijani labels (single place — no English in UI). */
export const CATEGORY_LABELS: Record<string, string> = {
  CAR: "Avtomobil",
  MOTORCYCLE: "Motosiklet",
};

export const SORT_LABELS: Record<SearchSort, string> = {
  NEWEST: "Ən yeni",
  PRICE_ASC: "Qiymət: artan",
  PRICE_DESC: "Qiymət: azalan",
  YEAR_DESC: "İl: yenidən köhnəyə",
};

export const STATUS_LABELS = {
  SOLD: "Satılıb",
  EXPIRED: "Müddəti bitib",
} as const;

export const UI = {
  brand: "AVTOSH.AZ",
  listings: "Elanlar",
  cars: "Avtomobillər",
  motorcycles: "Motosikletlər",
  postListing: "Elan yerləşdir",
  login: "Daxil ol",
  search: "Axtar",
  brandLabel: "Marka",
  modelLabel: "Model",
  modelVariantLabel: "Alt model",
  city: "Şəhər",
  price: "Qiymət",
  year: "Buraxılış ili",
  mileage: "Yürüş",
  showMore: "Daha çox göstər",
  clearFilters: "Filterləri təmizlə",
  applyFilters: "Tətbiq et",
  filters: "Filterlər",
  sort: "Sıralama",
  premium: "Premium elanlar",
  promoted: "Reklam",
  premiumBadge: "Premium",
  boostedBadge: "Reklam",
  loading: "Yüklənir…",
  noResults: "Uyğun elan tapılmadı",
  noResultsHint: "Filterləri dəyişin və ya təmizləyin.",
  errorTitle: "Xəta baş verdi",
  errorHint: "Zəhmət olmasa bir az sonra yenidən cəhd edin.",
  invalidFilters: "Axtarış parametrləri düzgün deyil",
  notFoundTitle: "Elan tapılmadı",
  notFoundHint: "Bu elan mövcud deyil və ya artıq göstərilmir.",
  backHome: "Ana səhifəyə qayıt",
  showPhone: "Nömrəni göstər",
  callSeller: "Zəng et",
  whatsapp: "WhatsApp ilə yaz",
  contactUnavailable: "Əlaqə məlumatı mövcud deyil",
  contactRateLimited: "Çox sayda cəhd edildi. Bir az sonra yenidən yoxlayın.",
  seller: "Satıcı",
  description: "Təsvir",
  features: "Təchizat",
  noAccident: "Vuruğu yoxdur",
  notRepainted: "Rənglənməyib",
  conditionTitle: "Avtomobil vəziyyəti",
  engineCcTitle: "Mühərrikin həcmi, sm³",
  specs: "Xüsusiyyətlər",
  any: "Hamısı",
  min: "min",
  max: "maks",
  credit: "Kredit",
  barter: "Barter",
  imageUnavailable: "Şəkil yoxdur",
  photoOf: "Şəkil",
  // Auth & favorites (Phase 4.10)
  loginTitle: "Daxil ol və ya qeydiyyatdan keç",
  loginHint: "WhatsApp təsdiq kodunu bu nömrəyə göndərəcəyik.",
  phoneLabel: "Mobil nömrə",
  phonePlaceholder: "010 218 41 91",
  sendCode: "Kod göndər",
  otpLabel: "Təsdiq kodu",
  otpHint: "WhatsApp-a göndərilən 6 rəqəmli kodu daxil edin.",
  otpSentTo: "Kod göndərildi:",
  verify: "Təsdiqlə",
  resend: "Kodu yenidən göndər",
  resendIn: "Yenidən göndərmə:",
  changePhone: "Nömrəni dəyiş",
  invalidPhone: "Mobil nömrəni düzgün formatda daxil edin. Məsələn: 010 218 41 91",
  otpInvalid: "Kod düzgün deyil. Yenidən cəhd edin.",
  otpExpired: "Kodun müddəti bitib. Yeni kod istəyin.",
  otpLocked: "Çox sayda səhv cəhd. Yeni kod istəyin.",
  otpRateLimited: "Çox sayda cəhd edildi. Bir az sonra yenidən yoxlayın.",
  logout: "Çıxış",
  profile: "Profil",
  favorites: "Seçilmişlər",
  favoritesEmpty: "Hələ seçilmiş elanınız yoxdur",
  favoritesEmptyHint: "Bəyəndiyiniz elanları ürək işarəsi ilə yadda saxlayın.",
  addFavorite: "Seçilmişlərə əlavə et",
  removeFavorite: "Seçilmişlərdən çıxar",
  listingInactive: "Elan artıq aktiv deyil",
  account: "Hesabım",
  accountBlocked: "Hesabınız bloklanıb. Baxış mümkündür, yeni əməliyyatlar məhdudlaşdırılıb.",
  myListings: "Elanlarım",
} as const;

/** Seller wizard & My Listings strings (Phase 4.11). */
export const SELLER = {
  newListing: "Yeni elan",
  // O.9 AXIN flow (sealed handoff wording)
  autosaveHint: "Qaralama avtomatik saxlanılır",
  quickStartTitle: "Sürətli başlanğıc",
  quickStartStart: "Başla →",
  sectionDetails: "Detallar",
  sectionSale: "Satış məlumatları",
  sectionPhotos: "Şəkillər",
  sectionExtras: "Əlavə məlumat",
  sectionContact: "Əlaqə məlumatları",
  // O.10 (sealed): combined stage title, sequential CTA, journey chip
  sectionInfoContact: "Əlavə məlumat və əlaqə",
  continueCta: "Davam et",
  fixCta: "Düzəlt",
  stageWord: "Mərhələ",
  detailsOptionalHint: "Bütün sahələr istəyə bağlıdır — boş keçə bilərsiniz",
  attentionRequired: "Tələb olunan məlumat çatışmır",
  attentionPhotos: "Minimum 3 şəkil tələb olunur",
  attentionContact: "Ad və əlaqə nömrəsi tələb olunur",
  subgroupOptional: "istəyə bağlıdır",
  subgroupRequired: "mütləqdir",
  sectionReview: "Baxış və dərc",
  sectionComplete: "Bölməni tamamla",
  sectionEdit: "Dəyiş",
  progressDone: "tamam",
  noResults: "Nəticə tapılmadı",
  brandFirstHint: "Marka seçin",
  searchTypeahead: "Axtar…",
  sellerName: "Satıcının adı",
  sellerNameHint: "elanda görünür",
  sellerNamePlaceholder: "Ad daxil edin",
  // O.10 combined-stage intro (combined-stage.md — supersedes the
  // longer O.9 copy for this stage)
  contactIntro: "Alıcıların sizinlə əlaqəsi üçün. Giriş nömrənizə təsir etmir.",
  contactPhoneListingOnly: "Bu nömrə yalnız bu elan üçün əlaqə nömrəsidir.",
  contactPhoneLocalHint: "yerli formatda yazın — 010 218 41 91",
  contactPhoneIncomplete: "Nömrə natamamdır — Azərbaycan nömrəsi 9 rəqəmdir",
  sellerNameRequired: "Ad mütləqdir",
  useProfileName: "Profil adımı istifadə et:",
  useLoginPhone: "Giriş nömrəmi istifadə et:",
  reviewFeeTitle: "Elanın yerləşdirilməsi",
  reviewFeeFree: "Pulsuz",
  reviewContactTitle: "ƏLAQƏ",
  promoModuleTitle: "Elanınızı önə çıxarın",
  promoOptionalHint: "istəyə bağlı",
  promoPreActive: "Seçiminiz elan aktiv olduqdan sonra tətbiq edilə bilər.",
  promoSkip: "Təşviqsiz davam et",
  promoContinueIntent: "Seçdiyiniz təşviqə davam et",
  categorySwitchConfirm:
    "Kateqoriya dəyişdikdə marka, model və kateqoriyaya aid seçimlər silinəcək. Davam edilsin?",
  claimsDeclarationHint: "satıcının bəyanı",
  featuresSelect: "Təchizat seç",
  // O.12 seller listing management (09-copy.md — verbatim contract)
  statusDeactivated: "Deaktiv",
  chipEditDraft: "Redaktə saxlanılıb",
  chipEditPending: "Dəyişiklik moderasiyadadır",
  chipEditCorrection: "Redaktəyə düzəliş tələb olunur",
  chipEditApproved: "Dəyişiklik təsdiqlənib",
  chipDeactivatedDraft: "Redaktə tamamlanmayıb",
  afterModeration: "Moderasiya sonrası aktivləşəcək",
  actionDeactivate: "Deaktiv et",
  actionActivate: "Aktiv et",
  deactivateDialogTitle: "Elanı deaktiv etmək istəyirsiniz?",
  deactivateDialogBody: "Elan platformada görünməyəcək. 30 günlük müddət dayanmayacaq. Aktiv Premium / Boost müddəti dayanmayacaq.",
  deactivateDialogCancel: "Ləğv et",
  toastDeactivated: "Elan deaktiv edildi",
  toastActivated: "Elan aktivləşdirildi",
  activateWithDraftNotice: "Elanı aktivləşdirmək üçün dəyişiklikləri tamamlayın və moderasiyaya göndərin.",
  lifecycleConflict: "Elan başqa sessiyada dəyişdirilib. Səhifəni yeniləyin.",
  deactivatedMeta: "Platformada görünmür · müddət davam edir",
  filterDeactivated: "Deaktiv",
  // O.12 Stage C — revision-backed edit mode (09-copy.md — verbatim)
  actionEdit: "Redaktə et",
  actionContinueEdit: "Redaktəyə davam et",
  actionViewEdit: "Redaktəyə bax",
  actionFix: "Düzəliş et",
  actionRenewActivate: "Yenilə və aktivləşdir — 2 AZN",
  actionCancelEdit: "Redaktəni ləğv et",
  cancelEditDialogTitle: "Redaktəni ləğv etmək istəyirsiniz?",
  cancelEditDialogBody: "Saxlanılmış dəyişikliklər silinəcək və mövcud təsdiqlənmiş elan dəyişməyəcək.",
  cancelEditDialogBack: "Geri qayıt",
  toastEditSubmitted: "Dəyişikliklər moderasiyaya göndərildi",
  toastEditCancelled: "Redaktə ləğv edildi",
  editHeader: "Elanı redaktə et",
  stripActive: "Dəyişikliklər moderasiyadan sonra elanda görünəcək. Bu müddətdə mövcud elanınız aktiv qalacaq.",
  stripDeactivated: "Elan hazırda deaktivdir. Dəyişikliklər təsdiqləndikdən sonra onu aktivləşdirə bilərsiniz.",
  stripDeactivatedRequested: "Elan dəyişikliklər təsdiqləndikdən sonra aktivləşdiriləcək.",
  stripExpired: "Elanın müddəti bitib. Əvvəlcə dəyişiklikləri təsdiq üçün göndərin. Təsdiqdən sonra 2 AZN ödəməklə elanı yeniləyə bilərsiniz.",
  reviewSubmitEdit: "Dəyişiklikləri moderasiyaya göndər",
  reviewSubmitEditActivate: "Dəyişiklikləri moderasiyaya göndər və aktivləşdir",
  expiredRenewHint: "Təsdiqdən sonra elanınızı 2 AZN ödəməklə yeniləyə bilərsiniz.",
  expiredPendingHint: "Redaktə təsdiqləndikdən sonra yeniləmə mümkün olacaq.",
  pendingBar: "Moderasiya gözləyir",
  pendingSubmittedWord: "göndərilib",
  editNotAvailable: "Redaktə artıq mövcud deyil.",
  // O.11 grouped equipment selector
  equipmentNoneSelected: "Təchizat seçilməyib",
  equipmentSelectedWord: "təchizat seçilib",
  equipmentGroupSelectedWord: "seçilib",
  equipmentSearchPlaceholder: "Təchizat axtar...",
  equipmentSearchLabel: "Təchizat axtar",
  equipmentSearchClear: "Təmizlə",
  equipmentNoMatches: "Heç nə tapılmadı",
  equipmentNoMatchesHint: "Başqa açar söz yoxlayın.",
  equipmentClearSearch: "Axtarışı təmizlə",
  photoAddTile: "+ Əlavə et",
  photoDropHint: "və ya faylları bura sürüklə",
  photoMinimumSuffix: "minimum",
  photoNeededSuffix: "şəkil lazımdır",
  photoRetry: "yenidən cəhd ↻",
  continueDraft: "Davam et",
  editListing: "Redaktə et",
  fixListing: "Düzəliş et",
  viewListing: "Elana bax",
  createListing: "Elan yarat",
  chooseCategory: "Kateqoriya seçin",
  existingDrafts: "Yarımçıq elanlarınız",
  steps: ["Nəqliyyat", "Məlumatlar", "Şəkillər", "Təsvir və əlaqə", "Yoxla və göndər"],
  stepLabel: "Addım",
  back: "Geri",
  next: "İrəli",
  category: "Kateqoriya",
  brand: "Marka",
  model: "Model",
  modelVariant: "Alt model",
  modelFirstHint: "Model seçin",
  year: "Buraxılış ili",
  price: "Qiymət, AZN",
  mileage: "Yürüş, km",
  engineCc: "Mühərrik, sm³",
  conditionTitle: "Avtomobil vəziyyəti",
  noAccident: "Vuruğu yoxdur",
  notRepainted: "Rənglənməyib",
  city: "Şəhər",
  credit: "Kredit mümkündür",
  barter: "Barter mümkündür",
  features: "Təchizat",
  description: "Təsvir",
  descriptionHint: "Nəqliyyat vasitəsi haqqında ətraflı yazın (maks. 5000 simvol).",
  contactPhone: "Əlaqə nömrəsi",
  contactPhoneHint: "Alıcılar bu nömrəni görəcək, məsələn +994501234567.",
  select: "Seçin",
  notSelected: "Seçilməyib",
  saving: "Yadda saxlanılır…",
  saved: "Yadda saxlanıldı",
  saveError: "Yadda saxlanmadı. Yenidən cəhd edin.",
  conflictTitle: "Elan başqa pəncərədə dəyişdirilib.",
  conflictHint: "Davam etmək üçün son vəziyyəti yükləyin. Bu pəncərədəki yadda saxlanmamış dəyişikliklər itəcək.",
  conflictReload: "Son vəziyyəti yüklə",
  photos: "Şəkillər",
  addPhotos: "Şəkil əlavə et",
  photoFormats: "JPEG, PNG və ya WebP, maks. 12 MB. Minimum 3 şəkil tələb olunur.",
  photoUnsupported: "Bu format dəstəklənmir. JPEG, PNG və ya WebP seçin.",
  photoTooLarge: "Şəkil çox böyükdür (maks. 12 MB).",
  photoUploadFailed: "Şəkil yüklənmədi. Yenidən cəhd edin.",
  photoUploading: "Yüklənir…",
  photoProcessing: "Emal olunur…",
  photoLimitReached: "Maksimum şəkil sayına çatdınız.",
  primaryPhoto: "Əsas şəkil",
  makePrimary: "Əsas şəkil et",
  moveLeft: "Sola çək",
  moveRight: "Sağa çək",
  deletePhoto: "Şəkli sil",
  preview: "Önizləmə",
  completenessTitle: "Göndərməzdən əvvəl tamamlayın",
  completenessDone: "Elan göndərilməyə hazırdır",
  minPhotos: "Ən azı 3 şəkil",
  submit: "Elanı yerləşdir",
  resubmit: "Yenidən göndər",
  submitting: "Göndərilir…",
  submittedFree: "Elanınız moderasiyaya göndərildi",
  submittedFreeHint: "Yoxlamadan sonra elanınız dərc olunacaq. Nəticə barədə məlumat veriləcək.",
  paymentRequired: "Ödəniş tələb olunur",
  paymentRequiredHint: "İlk 3 elan pulsuzdur. Bu elanın dərci üçün ödəniş tələb olunur.",
  paymentAfterHint: "Ödənişdən sonra elanınız moderasiyaya göndəriləcək.",
  payNow: "Ödəniş et",
  payInitiating: "Ödəniş səhifəsi hazırlanır…",
  payInitFailed: "Ödəniş başladıla bilmədi. Bir az sonra yenidən cəhd edin.",
  paySuccessTitle: "Ödəniş uğurla tamamlandı",
  paySuccessHint: "Elanınız moderasiyaya göndərildi. Yoxlamadan sonra dərc olunacaq.",
  payPendingTitle: "Ödəniş hələ təsdiqlənməyib",
  payPendingHint: "Ödəniş etmisinizsə, bir az sonra yenidən yoxlayın. Kartınızdan vəsait çıxıbsa, təkrar ödəniş etməyin.",
  payFailedTitle: "Ödəniş tamamlanmadı",
  payFailedHint: "Ödəniş ləğv edildi və ya bank tərəfindən qəbul edilmədi. Yenidən cəhd edə bilərsiniz.",
  payRefundedTitle: "Ödəniş geri qaytarılıb",
  payRefundedHint: "Bu ödəniş geri qaytarılıb. Suallarınız üçün dəstəklə əlaqə saxlayın.",
  payCheckAgain: "Yenidən yoxla",
  payRetry: "Yenidən cəhd et",
  payCheckingTitle: "Ödəniş yoxlanılır",
  payUnknownTitle: "Ödəniş məlumatı tapılmadı",
  payUnknownHint: "Bu ödəniş bu hesabla əlaqələndirilməyib və ya keçid düzgün deyil.",
  promote: "İrəli çək",
  promotionTitle: "Elanı irəli çək",
  premiumDescription: "Elanınız ana səhifədəki Premium bölməsində göstərilir.",
  boostDescription: "Elanınız axtarışda uyğun nəticələrin yuxarısında göstərilir.",
  promotionConfirmTitle: "Sifarişi təsdiqləyin",
  promotionService: "Xidmət",
  promotionDuration: "Müddət",
  promotionPrice: "Qiymət",
  promotionDay: "gün",
  premiumActive: "Premium aktivdir",
  boostActive: "Boost aktivdir",
  promotionUntil: "tarixinədək",
  promotionQueuedHint: "Yeni müddət mövcud müddətin bitməsindən sonra əlavə olunacaq.",
  premiumActivated: "Premium aktiv edildi",
  boostActivated: "Boost aktiv edildi",
  promotionActivatedHint: "Elanınız seçilmiş müddət ərzində irəli çəkiləcək.",
  promotionNotAvailable: "Bu elan üçün irəli çəkmə hazırda mümkün deyil.",
  promotionPackagesUnavailable: "Təşviq paketləri hazırda əlçatan deyil.",
  promotionPackagesUnavailableHint: "Paketlər aktiv olan kimi bu səhifədə görünəcək.",
  promotionOnlyActiveHint: "İrəli çəkmə yalnız aktiv elanlar üçün mümkündür.",
  payGenericTitle: "Ödəniş statusu yoxlanıldı",
  payGenericHint: "Hesabınıza daxil olaraq elanınızın vəziyyətinə baxa bilərsiniz.",
  payCheckFailedTitle: "Ödəniş yoxlanıla bilmədi",
  payCheckFailedHint: "Bank ilə əlaqə müvəqqəti mümkün olmadı. Ödəniş vəziyyətiniz dəyişməyib.",
  quotaFreeRemaining: "Pulsuz elan haqqınız:",
  quotaFree: "Bu elan pulsuz dərc olunacaq (ilk 3 elan pulsuzdur).",
  quotaPaid: "Bu elanın dərci ödənişlidir:",
  moderationPending: "Elanınız moderasiyadadır",
  moderationPendingHint: "Yoxlama tamamlanan kimi nəticə görünəcək.",
  moderationFeedback: "Moderator rəyi",
  incompleteTitle: "Elan natamamdır",
  insufficientImages: "Şəkil sayı kifayət deyil — ən azı 3 təsdiqlənmiş şəkil lazımdır.",
  invalidCatalog: "Seçimlərdən biri artıq mövcud deyil. Kataloq seçimlərini yeniləyin.",
  blockedTitle: "Hesabınız bloklanıb",
  blockedHint: "Yeni elan yerləşdirmək və redaktə etmək mümkün deyil.",
  emptyMyListings: "Hələ elanınız yoxdur",
  emptyMyListingsHint: "İlk elanınızı bir neçə dəqiqəyə yerləşdirin.",
  filterAll: "Hamısı",
  filterActive: "Aktiv",
  filterModeration: "Moderasiya",
  filterDraft: "Qaralama",
  filterCorrection: "Düzəliş",
  photosCount: "şəkil",
  unsavedLeaveWarning: "Yadda saxlanmamış dəyişikliklər var.",
  renew: "Yenilə",
  renewalTitle: "Elanı yenilə",
  renewalHint: "Yeniləmə eyni elanı yenidən aktivləşdirir — elan nömrəsi, keçmiş və statistika dəyişmir.",
  renewalExpiredAt: "Bitmə tarixi",
  renewalAfterPayment: "Ödəniş bank tərəfindən təsdiqləndikdən sonra elanınız",
  renewalAfterPaymentTail: "gün müddətinə yenidən aktiv olacaq.",
  renewalPendingIntent: "Bu elan üzrə yeniləmə ödənişi artıq başladılıb — ödənişi tamamlayın.",
  renewalNotAvailable: "Bu elan üçün yeniləmə mümkün deyil.",
  renewalOnlyExpiredHint: "Yeniləmə yalnız müddəti bitmiş elanlar üçün mümkündür.",
  renewalPay: "Ödənişə keç",
  renewalSuccessTitle: "Elan yeniləndi",
  renewalSuccessHint: "Elanınız yenidən aktivdir.",
  renewalNewExpiry: "Yeni bitmə tarixi",
} as const;

export const SPEC_LABELS = {
  modelVariant: "Alt model",
  fuelType: "Yanacaq",
  transmission: "Sürətlər qutusu",
  bodyType: "Ban növü",
  driveType: "Ötürücü",
  motorcycleType: "Motosiklet növü",
  color: "Rəng",
  engineCc: "Mühərrik",
  mileage: "Yürüş",
  year: "Buraxılış ili",
  city: "Şəhər",
  credit: "Kredit",
  barter: "Barter",
} as const;

export const GROUP_LABELS: Record<string, string> = {
  FUEL_TYPE: "Yanacaq",
  TRANSMISSION: "Sürətlər qutusu",
  BODY_TYPE: "Ban növü",
  DRIVE_TYPE: "Ötürücü",
  MOTORCYCLE_TYPE: "Motosiklet növü",
  COLOR: "Rəng",
};

/** Moderator portal strings (Phase 4.14). Staff-facing Azerbaijani. */
export const STAFF = {
  portal: "Moderasiya",
  queue: "Moderasiya növbəsi",
  queueEmpty: "Növbə boşdur — yoxlanılacaq elan yoxdur.",
  queueError: "Növbə yüklənmədi. Yenidən cəhd edin.",
  loadMore: "Daha çox göstər",
  submittedAt: "Göndərilib",
  seller: "Satıcı",
  review: "Elan yoxlaması",
  claim: "Nəzarətə götür",
  claimMine: "Sizin nəzarətinizdədir",
  claimOther: "Başqa moderatorun nəzarətindədir",
  claimFree: "Nəzarətdə deyil",
  claimUntil: "qədər",
  claimTaken: "Elan başqa moderator tərəfindən götürüldü.",
  claimRequired: "Qərar vermək üçün əvvəlcə elanı nəzarətə götürün.",
  approve: "Təsdiqlə",
  reject: "Rədd et",
  correction: "Düzəliş tələb et",
  suspend: "Dayandır",
  reason: "Səbəb",
  sellerNote: "Satıcı üçün qeyd",
  sellerNoteHint: "Bu mətn satıcıya olduğu kimi göstəriləcək. Maks. 1000 simvol.",
  confirmAction: "Təsdiq edin",
  confirm: "Bəli, təsdiqlə",
  cancel: "İmtina",
  approvedDone: "Elan təsdiqləndi və dərc olundu.",
  rejectedDone: "Elan rədd edildi.",
  correctionDone: "Düzəliş tələbi satıcıya göndərildi.",
  suspendedDone: "Elan dayandırıldı.",
  staleConflict: "Elan dəyişdirilib. Son versiyanı yeniləyin.",
  decisionAlready: "Bu elan üzrə qərar artıq verilib.",
  refresh: "Yenilə",
  actionFailed: "Əməliyyat alınmadı. Yenidən cəhd edin.",
  backToQueue: "Moderasiya növbəsinə qayıt",
  viewCurrent: "Cari vəziyyətə bax",
  history: "Moderasiya tarixçəsi",
  historyEmpty: "Əvvəlki yoxlama yoxdur.",
  decisionApproved: "Təsdiqlənib",
  decisionRejected: "Rədd edildi",
  decisionCorrection: "Düzəliş tələb olunub",
  images: "Şəkillər",
  primaryTag: "Əsas",
  noImage: "Şəkil yoxdur",
  descriptionTitle: "Təsvir",
  contactField: "Əlaqə nömrəsi",
  logout: "Çıxış",
  roleModerator: "Moderator",
  roleAdmin: "Admin",
  // O.12 Stage D — edit moderation (06-moderator-diff.md / 09-copy.md)
  tagNewListing: "YENİ ELAN",
  tagListingEdit: "ELAN REDAKTƏSİ",
  editReviewTitle: "Dəyişikliklərin müqayisəsi",
  editReviewLegend: "Mövcud elan → Təklif olunan dəyişiklik",
  diffAdded: "Əlavə edildi",
  diffRemoved: "Silindi",
  diffNewPrimary: "Yeni əsas şəkil",
  diffBefore: "Əvvəl",
  diffAfter: "Sonra",
  diffUnchanged: "Digər məlumatlar (dəyişməyib)",
  diffYes: "Bəli",
  diffNo: "Yox",
  diffReordered: "Şəkillərin sırası dəyişib",
  editApprovedDone: "Dəyişikliklər təsdiqləndi.",
  editRejectedDone: "Dəyişikliklər rədd edildi.",
  editCorrectionDone: "Düzəliş tələbi satıcıya göndərildi.",
  editCtxDeactivated:
    "Elan deaktivdir — təsdiqdən sonra yalnız aktivləşdirmə şərtləri ödənərsə yayımlanacaq.",
  editCtxExpired:
    "Elanın müddəti bitib — təsdiq məzmunu yeniləyəcək, elan yenilənənədək yayımlanmayacaq.",
  // O.13 Stage A — full review read model (11-copy-contract + approved IA)
  fullData: "Elanın bütün məlumatları",
  layerCurrent: "Mövcud elan",
  layerProposed: "Təklif olunan dəyişiklik",
  secVehicleCar: "Avtomobil məlumatları",
  secVehicleMoto: "Motosiklet məlumatları",
  secSales: "Satış məlumatları",
  secCondition: "Vəziyyət",
  secEquipment: "Təchizat",
  secSellerContact: "Satıcı / Əlaqə",
  equipmentEmpty: "Təchizat seçilməyib",
  // O.13 Stage B — moderator edit foundation (11-copy-contract)
  editEnter: "Redaktə et",
  editSave: "Yadda saxla",
  editCancel: "Dəyişiklikləri ləğv et",
  adjSaved: "Moderator düzəlişi saxlanılıb",
  adjSavedBy: "Saxlayan moderator",
  layerSeller: "Seller tərəfindən daxil edilib",
  layerModerator: "Moderator düzəlişi",
  editContextStrip:
    "Moderator redaktə rejimi — dəyişikliklər satıcının müraciətini dəyişmir və dərc olunmur",
  depResetWarning: "Model, ban növü və təchizat seçimləri sıfırlanacaq",
  equipMarkerAdded: "əlavə edildi",
  equipMarkerRemoved: "çıxarıldı",
  photoPrimary: "Əsas şəkil",
  photoRemove: "Şəkli çıxar",
  photoRestore: "Geri qaytar",
  photoSetPrimary: "Əsas şəkil et",
  photoMoveUp: "Yuxarı",
  photoMoveDown: "Aşağı",
  photoMinError: "Ən azı 3 şəkil qalmalıdır — yadda saxlamaq mümkün deyil",
  takeoverContinue: "Davam et",
  takeoverDiscard: "Düzəlişi sil",
  takeoverBanner: "Bu elanda saxlanılmış moderator düzəlişi var.",
  takeoverNote: "Claim artıq sizindir — bu, əvvəlki moderatorun saxlanılmış işidir.",
  takeoverDiscardConfirm: (name: string): string =>
    `${name}-ın saxlanılmış düzəlişi silinəcək və tarixçədə qalacaq. Bu geri qaytarıla bilməz.`,
  unsavedTitle: "Saxlanmamış dəyişikliklər var",
  unsavedBody: "Redaktə rejimindən çıxsanız, saxlanmamış dəyişikliklər itəcək.",
  unsavedBack: "Redaktəyə qayıt",
  unsavedDiscard: "Dəyişiklikləri at",
  conflictBody: "Elan başqa sessiyada dəyişdirilib. Səhifəni yeniləyin.",
  conflictAction: "Səhifəni yenilə",
  decisionsBlockedUnsaved: "Saxlanmamış dəyişikliklər var — qərarlar bağlıdır.",
  historyAdjSaved: "Moderator düzəlişi saxladı",
  historyAdjDiscarded: "Moderator düzəlişi sildi",
  // O.13 Stage C — adjusted NEW decisions (sealed 11-copy-contract)
  approveWithAdj: "Moderator düzəlişləri ilə təsdiqlənəcək",
  correctionWithAdj:
    "Moderator düzəlişləri tətbiq olunmayacaq. Satıcı düzəliş sorğusunu alacaq; saxlanılmış moderator düzəlişi tarixçəyə köçürüləcək.",
  rejectWithAdj:
    "Moderator düzəlişləri tətbiq olunmayacaq. Rədd mövcud qaydalarla icra olunacaq; düzəliş yalnız tarixçədə qalacaq.",
  decisionAdjustmentInvalid:
    "Moderator düzəlişi natamamdır və ya etibarsız seçim ehtiva edir — redaktəyə qayıdıb düzəldin.",
} as const;

/** Admin panel strings (Phase 4.15). */
export const ADMIN = {
  panel: "Admin panel",
  dashboard: "İdarə paneli",
  users: "İstifadəçilər",
  staff: "Əməkdaşlar",
  listings: "Elanlar",
  payments: "Ödənişlər",
  packages: "Təşviq paketləri",
  catalog: "Kataloq",
  reports: "Şikayətlər",
  audit: "Audit jurnalı",
  settings: "Tənzimləmələr",
  search: "Axtar",
  phoneSearch: "Telefon nömrəsi",
  nextPage: "Növbəti səhifə",
  empty: "Nəticə tapılmadı",
  status: "Status",
  role: "Rol",
  created: "Yaradılıb",
  lastLogin: "Son giriş",
  listingsCount: "Elan sayı",
  blocked: "Bloklanıb",
  active: "Aktiv",
  block: "Blokla",
  unblock: "Bloku götür",
  blockReason: "Səbəb",
  blockConfirm: "İstifadəçi bloklansın?",
  blockHint: "Bloklanan istifadəçi baxa bilər, lakin yeni elan, redaktə, ödəniş və təşviq edə bilməz.",
  unblockConfirm: "Blok götürülsün?",
  grantModerator: "Moderator təyin et",
  revokeModerator: "Moderatorluğu götür",
  grantAdmin: "Admin təyin et",
  revokeAdmin: "Adminliyi götür",
  roleConfirm: "Rol dəyişikliyi təsdiqlənsin?",
  unsuspend: "Bərpa et",
  unsuspendConfirm: "Elan bərpa edilsin?",
  unsuspendHint: "Yerləşdirmə müddəti bitibsə, elan AKTİV yox, MÜDDƏTİ BİTMİŞ statusuna keçəcək. Ödənilmiş müddətlər uzadılmır.",
  verifyPayment: "Provayderdə yoxla",
  verifyConfirm: "Ödəniş provayder üzərindən yoxlansın?",
  attempts: "Provayder cəhdləri",
  refundBlocked: "Geri qaytarma başlatma bağlıdır — rəsmi provayder müqaviləsi tələb olunur.",
  price: "Qiymət",
  priceAzn: "Qiymət (AZN)",
  save: "Yadda saxla",
  activate: "Aktivləşdir",
  deactivate: "Deaktiv et",
  activateConfirm: "Paket satışa açılsın?",
  deactivateConfirm: "Paket satışdan çıxarılsın?",
  editConflict: "Məlumat başqa admin tərəfindən dəyişdirilib. Səhifəni yeniləyin.",
  refresh: "Yenilə",
  saved: "Yadda saxlanıldı",
  actionFailed: "Əməliyyat alınmadı.",
  settingValue: "Dəyər",
  settingConfirm: "Tənzimləmə dəyişikliyi təsdiqlənsin?",
  settingHint: "Dəyişiklik yalnız gələcək əməliyyatlara təsir edir; mövcud ödənişlər dəyişməz.",
  reportOpen: "Açıq",
  reportResolved: "Həll edilib",
  reportDismissed: "Bağlandı",
  resolve: "Həll edildi",
  dismiss: "Əsassızdır",
  reportConfirm: "Şikayət bağlansın?",
  viewListing: "Elana bax",
  action: "Əməliyyat",
  actor: "İcraçı",
  entity: "Obyekt",
  filter: "Filtr",
  all: "Hamısı",
  logoutLabel: "Çıxış",
  moderatorPortal: "Moderasiya",
} as const;

/** Buyer-side listing report intake (Phase 4.16). */
export const REPORT = {
  action: "Şikayət et",
  title: "Elan barədə şikayət",
  reason: "Səbəb",
  note: "Qeyd (istəyə bağlı)",
  submit: "Göndər",
  cancel: "İmtina",
  success: "Şikayətiniz qəbul edildi. Təşəkkür edirik.",
  rateLimited: "Bu elan üzrə şikayət artıq qeydə alınıb və ya limit keçilib.",
  failed: "Şikayət göndərilə bilmədi. Yenidən cəhd edin.",
  reasons: {
    WRONG_INFORMATION: "Yanlış məlumat",
    DUPLICATE: "Təkrar elan",
    FRAUD_SUSPECTED: "Fırıldaqçılıq şübhəsi",
    SOLD_OR_UNAVAILABLE: "Satılıb və ya mövcud deyil",
    PROHIBITED_CONTENT: "Qadağan olunmuş məzmun",
    OTHER: "Digər",
  } as Record<string, string>,
} as const;
