import type { SearchSort } from "@/lib/config/marketplace";

/** Buyer-visible Azerbaijani labels (single place — no English in UI). */
export const CATEGORY_LABELS: Record<string, string> = {
  CAR: "Avtomobil",
  MOTORCYCLE: "Motosiklet",
};

export const SORT_LABELS: Record<SearchSort, string> = {
  NEWEST: "Ən yeni",
  PRICE_ASC: "Qiymət: artan",
  PRICE_DESC: "Qiymət: azalan",
  YEAR_DESC: "İl: yenidən köhnəyə",
};

export const STATUS_LABELS = {
  SOLD: "Satılıb",
  EXPIRED: "Müddəti bitib",
} as const;

export const UI = {
  brand: "AVTOSH.AZ",
  listings: "Elanlar",
  cars: "Avtomobillər",
  motorcycles: "Motosikletlər",
  postListing: "Elan yerləşdir",
  login: "Daxil ol",
  search: "Axtar",
  brandLabel: "Marka",
  modelLabel: "Model",
  city: "Şəhər",
  price: "Qiymət",
  year: "Buraxılış ili",
  mileage: "Yürüş",
  showMore: "Daha çox göstər",
  clearFilters: "Filterləri təmizlə",
  applyFilters: "Tətbiq et",
  filters: "Filterlər",
  sort: "Sıralama",
  premium: "Premium elanlar",
  promoted: "Reklam",
  premiumBadge: "Premium",
  boostedBadge: "Reklam",
  loading: "Yüklənir…",
  noResults: "Uyğun elan tapılmadı",
  noResultsHint: "Filterləri dəyişin və ya təmizləyin.",
  errorTitle: "Xəta baş verdi",
  errorHint: "Zəhmət olmasa bir az sonra yenidən cəhd edin.",
  invalidFilters: "Axtarış parametrləri düzgün deyil",
  notFoundTitle: "Elan tapılmadı",
  notFoundHint: "Bu elan mövcud deyil və ya artıq göstərilmir.",
  backHome: "Ana səhifəyə qayıt",
  showPhone: "Nömrəni göstər",
  callSeller: "Zəng et",
  whatsapp: "WhatsApp ilə yaz",
  contactUnavailable: "Əlaqə məlumatı mövcud deyil",
  contactRateLimited: "Çox sayda cəhd edildi. Bir az sonra yenidən yoxlayın.",
  seller: "Satıcı",
  description: "Təsvir",
  features: "Təchizat",
  specs: "Xüsusiyyətlər",
  any: "Hamısı",
  min: "min",
  max: "maks",
  credit: "Kredit",
  barter: "Barter",
  imageUnavailable: "Şəkil yoxdur",
  photoOf: "Şəkil",
  // Auth & favorites (Phase 4.10)
  loginTitle: "Daxil ol və ya qeydiyyatdan keç",
  loginHint: "Telefon nömrənizə WhatsApp ilə təsdiq kodu göndəriləcək.",
  phoneLabel: "Telefon nömrəsi",
  phonePlaceholder: "+994 50 123 45 67",
  sendCode: "Kod göndər",
  otpLabel: "Təsdiq kodu",
  otpHint: "WhatsApp-a göndərilən 6 rəqəmli kodu daxil edin.",
  otpSentTo: "Kod göndərildi:",
  verify: "Təsdiqlə",
  resend: "Kodu yenidən göndər",
  resendIn: "Yenidən göndərmə:",
  changePhone: "Nömrəni dəyiş",
  invalidPhone: "Telefon nömrəsi düzgün deyil.",
  otpInvalid: "Kod düzgün deyil. Yenidən cəhd edin.",
  otpExpired: "Kodun müddəti bitib. Yeni kod istəyin.",
  otpLocked: "Çox sayda səhv cəhd. Yeni kod istəyin.",
  otpRateLimited: "Çox sayda cəhd edildi. Bir az sonra yenidən yoxlayın.",
  logout: "Çıxış",
  profile: "Profil",
  favorites: "Seçilmişlər",
  favoritesEmpty: "Hələ seçilmiş elanınız yoxdur",
  favoritesEmptyHint: "Bəyəndiyiniz elanları ürək işarəsi ilə yadda saxlayın.",
  addFavorite: "Seçilmişlərə əlavə et",
  removeFavorite: "Seçilmişlərdən çıxar",
  listingInactive: "Elan artıq aktiv deyil",
  account: "Hesabım",
  accountBlocked: "Hesabınız bloklanıb. Baxış mümkündür, yeni əməliyyatlar məhdudlaşdırılıb.",
  sellerComingSoon: "Elan yerləşdirmə tezliklə əlavə olunacaq",
  sellerComingSoonHint: "Satıcı paneli üzərində işləyirik. Bu bölmə növbəti mərhələdə açılacaq.",
} as const;

export const SPEC_LABELS = {
  fuelType: "Yanacaq",
  transmission: "Sürətlər qutusu",
  bodyType: "Ban növü",
  driveType: "Ötürücü",
  motorcycleType: "Motosiklet növü",
  color: "Rəng",
  engineCc: "Mühərrik",
  mileage: "Yürüş",
  year: "Buraxılış ili",
  city: "Şəhər",
  credit: "Kredit",
  barter: "Barter",
} as const;

export const GROUP_LABELS: Record<string, string> = {
  FUEL_TYPE: "Yanacaq",
  TRANSMISSION: "Sürətlər qutusu",
  BODY_TYPE: "Ban növü",
  DRIVE_TYPE: "Ötürücü",
  MOTORCYCLE_TYPE: "Motosiklet növü",
  COLOR: "Rəng",
};
